theme: jekyll-theme-minimal

title: iSEQB.org
description: international Software Engineering Qualification Board

logo: https://user-images.githubusercontent.com/1764012/63192548-9ed05d80-c06b-11e9-862f-c2fce3d4c78a.png

is_user_page: false
is_project_page: true
